<template>
  <div class="page">
    <PageHeader title="Terms Of Use" subtitle="The Terms Of Use On This Page"/>
    <information title="Terms of Use" body="Please read the following Terms of Use and disclaimers carefully before using this website."></information>
    <information title="Acceptance of Terms" body="Borg Development Corp. maintains this website (the “Website”) for your personal entertainment, information, education and communication. Feel free to browse the Website, but please read these terms of use before doing so.
Your access to and use of the Website is subject to the following Terms of Use. Borg Development Corp. reserves the right to update the Terms of Use at any time without notice to you. You are bound by any such revisions and should therefore periodically visit this page to review the then current Terms of Use to which you are bound. The most current version of the Terms of Use may be accessed by clicking on the “Terms of Use” hypertext link located at the bottom of the Website. By using, accessing and browsing the Website, you signify your acceptance of the Terms of Use, without limitation or qualification. If you do not agree to these Terms of Use, then please do not use the Website.
"></information>
    <information title="Accuracy and Completeness of Information" body="While Borg Development Corp. uses reasonable efforts to include accurate and up to date information in the Website, Borg Development Corp. makes no warranties or representations as to the accuracy, correctness, reliability or otherwise with respect to such information, and assumes no liability or responsibility for any omissions or errors (including, without limitation, typographical errors and technical errors) in the content of the Website."></information>
    <information title="Modification of Website" body="Information in the Website is subject to change without notice. Information regarding Borg Development Corp.’s products and services is applicable only in Canada unless otherwise noted. Some products and services may not be available in certain areas. Borg Development Corp. makes no representations that the materials in this Website are appropriate or available for use in other countries aside from Canada. Those who do access this Website from other countries are solely responsible for compliance with local laws of that country."></information>
    <information title="Your Use of the Website" body="You may not modify, alter or change any materials or distribute, publish, transmit, reuse, re-post or use the content of the Website for public or commercial purposes, including, without limitation, the text, images, audio and video. Unauthorized use of the materials is strictly prohibited and is a violation of the rights of Borg Development Corp. and/or third parties, including, without limitation, under copyright laws, trademark laws, the laws of privacy and publicity."></information>
    <information title="Unsolicited Submissions" body="Although we are sincerely complimented that you thought to send us an idea or concept, we are unable to accept ideas and suggestions (“Submission”) from outside the company. We genuinely appreciate your interest, but do not want to foster false expectations as to the origin of any idea. If you do send us a Submission, despite our request not to do so, then such Submission will be considered non-confidential and non-proprietary and shall immediately become the property of Borg Development Corp."></information>
    <information title="Communication" body="From time to time, Borg Development Corp. may ask that you transmit to the Website by electronic mail your feedback on Borg Development Corp.’s products and/or services. Any communication or material you transmit, upload or post will be (a) treated as non-confidential and non-proprietary by Borg Development Corp.; (b) become the property of Borg Development Corp. and Borg Development Corp. shall exclusively now and hereinafter own all rights, title and interest therein; and (c) used without restriction by Borg Development Corp. or its bottlers, licensees and affiliates at its sole discretion without any obligation, compensation or other liability to you. Such use may be for any purpose whatsoever, including, but not limited to, reproduction, disclosure, transmission, publication, broadcast and posting whole or in part, in any medium and in any manner on this Website or otherwise. However, Borg Development Corp. shall be under no obligation to respond to any such communication.
In the event that Borg Development Corp. may, from time to time, allow for discussions, chats, postings, transmissions, bulletin board and the like on the Website, Borg Development Corp. is under no obligation to monitor or review such transmitted information and assumes no responsibility or liability arising from the content of any such locations nor for any error, defamation, libel, slander, omission, falsehood, obscenity, pornography, profanity, danger or inaccuracy of any such information. You are prohibited from posting or transmitting any unlawful, threatening, libelous, defamatory, obscene, scandalous, inflammatory, pornographic or profane material or any material that could constitute or encourage conduct that would be considered a criminal offense, give rise to civil liability or otherwise violate any law. Borg Development Corp. will fully cooperate with any law enforcement authorities or court order requesting or directing Borg Development Corp. to disclose the identity of anyone posting any such information or materials.
"></information>
    <information title="Privacy Policy" body="Borg Development Corp.’s use of any personal information you submit to the Website is governed by the Website’s Privacy Policy."></information>
    <information title="Disclaimers" body="Use of and browsing in the Website is done at user’s own risk. Neither Borg Development Corp. nor any other party involved in creating, producing or delivering the Website shall be liable for any direct, incidental, consequential, indirect or punitive damages arising out of your access to, or use of, or browsing the Website, or uploading content to the Website, or downloading of any materials, data, text, images, video or audio from the Website, including, without limitation, damage to, or viruses that may infect, your computer equipment or other property as a result thereof. Without limiting the foregoing, everything on the Website is provided to you “AS IS” WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NON-INFRINGEMENT. Please note that some jurisdictions may not allow the exclusion of implied warranties, so some of the above exclusions may not apply to you. Check your local laws for any restrictions or limitations regarding the exclusion of implied warranties."></information>
    <information title="Limitation of Liability" body="IN NO EVENT SHALL BORG DEVELOPMENT CORP., ITS AFFILIATES, AND THEIR RESPECTIVE OFFICERS, DIRECTORS, EMPLOYEES, OR AGENTS, BE LIABLE TO YOU FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, PUNITIVE, OR CONSEQUENTIAL DAMAGES WHATSOEVER RESULTING FROM YOUR USE OF THE WEBSITE, YOUR USE OF ANY THIRD PARTY SITE, OR THE ACTIONS OF ANY THIRD PARTY, HOWSOEVER ARISING, WHETHER BASED ON WARRANTY, CONTRACT, TORT, OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT THE COMPANY IS ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. THE FOREGOING LIMITATION OF LIABILITY SHALL APPLY TO THE FULLEST EXTENT PERMITTED BY LAW IN THE APPLICABLE JURISDICTION.
The Website is controlled and offered by Borg Development Corp.. Borg Development Corp. makes no representations that the Website is appropriate or available for use in other locations. Those who access or use the Website from other jurisdictions do so at their own volition and are responsible for compliance with local law.
"></information>
    <information title="Indemnification" body="You agree to indemnify and hold harmless Borg Development Corp., its affiliates, and their respective officers, directors, employees and agents, from and against any and all claims, losses, and expenses arising from your violation of these Terms of Use or of any third party right including, without limitation, any copyright, property, or privacy right."></information>
    <information title="Copyright Notice" body="You should assume that all materials, designs, text and images contained in the Website (collectively, the “Materials”) are copyrighted property of Borg Development Corp. or related entities. Borg Development Corp. neither warrants nor represents that your use of these Materials will not infringe rights of third parties unrelated to Borg Development Corp.."></information>
    <information title="Trade-marks and Proprietary Materials" body="This Website contains many valuable trademarks, names, titles, logos, images, designs, and other proprietary materials that are owned or used under licence by Borg Development Corp. (the “Trade-marks”). Nothing contained on the Website should be construed as granting, by implication, estoppel or otherwise, any license or right to use any of these Trade-marks. If you misuse any Trade-mark in violation of these Terms of Use, Borg Development Corp. will aggressively enforce its intellectual property rights to the fullest extent of the law, including the seeking of criminal prosecution."></information>
    <information title="Offers" body="All offers set forth on the Website are void where prohibited, and are subject to the posting of any official rules pertaining to such offers."></information>
    <information title="Links to Third Party Sites" body="This Website may link to other sites not maintained by or related to Borg Development Corp.. Such hyperlinks are provided as a service to users and are not sponsored by, endorsed or otherwise affiliated with this Website or with the products and services of Borg Development Corp.. Borg Development Corp. has not reviewed all of the sites linked to the Website and is not responsible for the content of any off-site pages or links to any other sites. Viewing all other sites is at your own risk."></information>
    <information title="Jurisdiction" body="These Terms of Use are governed and interpreted under the laws of the Province of Ontario. If any portion of these Terms of Use is deemed unlawful, void or unenforceable, then that part shall be deemed severable and will not effect the validity and enforceability of any remaining provisions.
These Terms of Use, together with the Privacy Policy and any other legal notices published by Borg Development Corp. on the Website, shall constitute the entire agreement between you and Borg Development Corp. with respect to the Website. You acknowledge that any other agreements between you and Borg Development Corp. with respect to the Website are superseded and of no force or effect.
"></information>
  </div>
</template>

<script>
export default {
  name: "terms"
}
</script>

<style scoped>
.page{
  display: flex;
  flex-direction: column;
  -ms-flex-align: center;
}
</style>
